name: ebpf-exporter
version: 0.0.6
services:
  ebpf-exporter-asqeu:
    annotations: {}
    apiVersion: apps/v1
    dependsOn: []
    id: null
    isAnnotation: null
    labels:
      app.kubernetes.io/instance: ebpf-exporter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ebpf-exporter
    model: kubernetes
    name: ebpf-exporter
    namespace: default
    settings:
      spec:
        selector:
          match Labels:
            app.kubernetes.io/instance: ebpf-exporter
            app.kubernetes.io/name: ebpf-exporter
        template:
          metadata:
            labels:
              app.kubernetes.io/instance: ebpf-exporter
              app.kubernetes.io/name: ebpf-exporter
              checksum/config: 638565adaf0af3ae5a96efff1567a8e662779bfc73ebd86dcaef55edca0644d
          spec:
            containers:
            - args:
              - --config.file
              - /etc/ebpf_exporter/config.yaml
              - --web.listen-address
              - 0.0.0.0:9435
              command:
              - /usr/local/bin/ebpf_exporter
              image: teacherspayteachers/ebpf-exporter:1.2.3
              image Pull Policy: IfNotPresent
              name: ebpf-exporter
              ports:
              - container Port: 9435
                name: metrics
                protocol: TCP
              security Context:
                privileged: true
              volume Mounts:
              - mount Path: /etc/ebpf_exporter
                name: config
              - mount Path: /sys/kernel/debug
                name: kernel
              - mount Path: /lib/modules/
                name: modules
            dns Policy: ClusterFirst
            restart Policy: Always
            scheduler Name: default-scheduler
            volumes:
            - config Map:
                default Mode: 420
                name: ebpf-exporter
              name: config
            - host Path:
                path: /sys/kernel/debug
                type: Directory
              name: kernel
            - host Path:
                path: /lib/modules/
                type: Directory
              name: modules
    traits:
      meshmap:
        edges: []
        fieldRefData: {}
        id: c879863a-5b2a-41ae-963d-040dfa0e2a10
        meshmodel-metadata:
          capabilities: |2-
             {
              "designer": {
                "edit": {
                  "shape": {
                    "convert-shape": false
                  }
                }
              }
            }
          defaultData: ""
          genealogy: parent
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: Created by Meshery Authors
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: circle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-opacity: 0.5
            border-width: 2
            z-index: 4
          styles: '{"border-width":2,"background-opacity":0.5}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/daemonset-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/daemonset-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/daemonset-white.svg
        position:
          posX: 36
          posY: -35.5
        whiteboardData:
          style: {}
    type: DaemonSet
    version: ""
  ebpf-exporter-fhjll:
    annotations: {}
    apiVersion: v1
    dependsOn: []
    id: null
    isAnnotation: null
    labels:
      app.kubernetes.io/instance: ebpf-exporter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ebpf-exporter
    model: kubernetes
    name: ebpf-exporter
    namespace: default
    settings:
      data:
        config.yaml: |2

          []
    traits:
      meshmap:
        edges: []
        fieldRefData: {}
        id: bb368165-fe34-434f-ba6c-aff8397a801d
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: bottom-round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides: ""
          styles: ""
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/configmap-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/configmap-white.svg
        position:
          posX: -36
          posY: 39
        whiteboardData:
          style: {}
    type: ConfigMap
    version: ""
  ebpf-exporter-fkebp:
    annotations: {}
    apiVersion: v1
    dependsOn: []
    id: null
    isAnnotation: null
    labels:
      app.kubernetes.io/instance: ebpf-exporter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ebpf-exporter
    model: kubernetes
    name: ebpf-exporter
    namespace: default
    settings:
      spec:
        ports:
        - port: 80
          protocol: TCP
          target Port: metrics
        selector:
          app.kubernetes.io/instance: ebpf-exporter
          app.kubernetes.io/name: ebpf-exporter
        type: ClusterIP
    traits:
      meshmap:
        edges: []
        fieldRefData: {}
        id: 9a4c0431-36e2-4df6-886b-8bff08b9394e
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-position-y: 4.5
            height: 20
            padding: 12
            width: 20
            x: 10px
            "y": 12px
            z-index: 3
          styles: '{"height":20,"width":20,"padding":12,"background-position-y":4.5,"x":"10px","y":"12px"}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/service-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/service-white.svg
        position:
          posX: -36
          posY: -30
        whiteboardData:
          style: {}
    type: Service
    version: ""
